#cretaing pv is k8 admin job
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - readWriteOnce
  persistentVolumeclaimPolicy: Retain #retain means don't delete data,recycle means delete data not disk,delete means delete the disk directly
  capac ity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHnadle: vol:id
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: ebs-static
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ebs-static
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 30009