apiVersion: v1
kind: pod
metadata:
  name: resources
  labels:
    project: roboshop
    environment: dev
spec:
  contianers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "68Mi"
          cpu: "100m" # 1/10th of cpu
          #provide eaual or more than requests
          limits:
            memory: "100Mi"
            cpu: "120m"