apiVersion: v1
kind: Pod
metedata:
  name: service-demo
  #this labels are used to register this pod with service
labels:
  project: roboshop
  component: frontend
  environment: dev
spec:
  containers:
  - name: nginx
    image: nginx