apiVersion: v1
kind: service
metadata:
  name: nginx-np
spec: 
  type: NodePort
  selector: robsohop
  component: frontend
  environment: dev
  purpose: node-port
ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
