apiVersion: v1
kind: pod
metadata:
  name: service-np-demo
  labels: 
    project: roboshop
    component:  frontend
    environment:  dev
    purpose: node-port
spec: 
  containers:
    - name: nginx
      image: nginx
      